#ifndef S_DS_01_CHECK_BALANCED_PARENTHESIS_MAIN_H
#define S_DS_01_CHECK_BALANCED_PARENTHESIS_MAIN_H

#include <stdio.h>
#include "balanced.h"

#define ARRAY_SIZE 50

#endif //S_DS_01_CHECK_BALANCED_PARENTHESIS_MAIN_H
